Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> [rel] Running /usr/local/google/buildbot/src/android/emu-master-dev/external/qemu/android/scripts/unix/gen-android-sdk-toolchain.sh '--host=linux-x86_64' '/usr/local/google/buildbot/src/android/emu-master-dev/out/build/emulator/build/default/toolchain' '' '--aosp-dir=/usr/local/google/buildbot/src/android/emu-master-dev' '--aosp-clang_ver=clang-r346389c' '--verbosity=2'
> [rel] CMake Error at android/build/cmake/toolchain.cmake:55 (message):
> [rel]   Unable to retrieve sdk info from
> [rel]   /usr/local/google/buildbot/src/android/emu-master-dev/external/qemu/android/scripts/unix/gen-android-sdk-toolchain.sh
> [rel]   --host=linux-x86_64
> [rel]   /usr/local/google/buildbot/src/android/emu-master-dev/out/build/emulator/build/default/toolchain
> [rel]   : ,
> [rel]   /usr/local/google/buildbot/src/android/emu-master-dev/external/qemu/android/scripts/unix/gen-android-sdk-toolchain.sh:
> [rel]   620:
> [rel]   /usr/local/google/buildbot/src/android/emu-master-dev/external/qemu/android/scripts/unix/gen-android-sdk-toolchain.sh:
> [rel]   [[: not found
> [rel] 
> [rel] Call Stack (most recent call first):
> [rel]   android/build/cmake/toolchain.cmake:88 (toolchain_cmd)
> [rel] -- Configuring incomplete, errors occurred!
> [rel]   android/build/cmake/toolchain.cmake:123 (toolchain_generate_internal)
> [rel]   android/build/cmake/toolchain-linux-x86_64.cmake:27 (toolchain_generate)
> [rel]   /usr/local/google/buildbot/src/android/emu-master-dev/prebuilts/cmake/linux-x86/share/cmake-3.5/Modules/CMakeDetermineSystem.cmake:98 (include)
> [rel]   CMakeLists.txt
> [rel] 
> [rel] 
> [rel] CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
> [rel] CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
> [rel] Traceback (most recent call last):
> [rel]   File "/usr/local/google/buildbot/src/android/emu-master-dev/external/qemu/android/build/python/cmake.py", line 20, in <module>
> [rel]     cmake.launch()
> [rel]   File "/usr/local/google/buildbot/src/android/emu-master-dev/external/qemu/android/build/python/aemu/cmake.py", line 145, in launch
> [rel]     app.run(main)
> [rel]   File "/home/android-build/.local/lib/python2.7/site-packages/absl_py-0.7.0-py2.7.egg/absl/app.py", line 300, in run
> [rel]     _run_main(main, args)
> [rel]   File "/home/android-build/.local/lib/python2.7/site-packages/absl_py-0.7.0-py2.7.egg/absl/app.py", line 251, in _run_main
> [rel]     sys.exit(main(argv))
> [rel]   File "/usr/local/google/buildbot/src/android/emu-master-dev/external/qemu/android/build/python/aemu/cmake.py", line 121, in main
> [rel]     configure()
> [rel]   File "/usr/local/google/buildbot/src/android/emu-master-dev/external/qemu/android/build/python/aemu/cmake.py", line 101, in configure
> [rel]     run(cmake_cmd, FLAGS.out)
> [rel]   File "/usr/local/google/buildbot/src/android/emu-master-dev/external/qemu/android/build/python/aemu/process.py", line 96, in run
> [rel]     (' '.join(cmd), proc.returncode))
> :emulator:buildDefaultEmulator FAILED
> :emulator:buildDefaultEmulator (Thread[main,5,main]) completed. Took 6.502 secs.
> [rel] Exception: Failed to run /usr/local/google/buildbot/src/android/emu-master-dev/prebuilts/cmake/linux-x86/bin/cmake -B/usr/local/google/buildbot/src/android/emu-master-dev/out/build/emulator/build/default -DCMAKE_TOOLCHAIN_FILE=/usr/local/google/buildbot/src/android/emu-master-dev/external/qemu/android/build/cmake/toolchain-linux-x86_64.cmake -DOPTION_CRASHUPLOAD=PROD -DANDROID_SYMBOL_URL=https://clients2.google.com/cr/symbol -DCMAKE_BUILD_TYPE=Release -DQTWEBENGINE=False -DOPTION_SDK_TOOLS_REVISION=28.1.5 -DOPTION_SDK_TOOLS_BUILD_NUMBER=P7632519 -G Ninja /usr/local/google/buildbot/src/android/emu-master-dev/external/qemu - 1
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':emulator:buildDefaultEmulator'.
> > Failed to run android/buid/python/cmake.py command. See console output
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.
> 
> BUILD FAILED
> 
> Total time: 15.571 secs
> Traceback (most recent call last):
>   File "tools/buildSrc/servers/build_tools.py", line 135, in <module>
>     main(sys.argv)
>   File "tools/buildSrc/servers/build_tools.py", line 131, in main
>     run([gradle, '-b', build_gradle, '--no-daemon', '--info', 'dist', sdk], env)
>   File "tools/buildSrc/servers/build_tools.py", line 70, in run
>     (' '.join(cmd), proc.returncode))
> Exception: Failed to run /usr/local/google/buildbot/src/android/emu-master-dev/tools/gradlew -b /usr/local/google/buildbot/src/android/emu-master-dev/tools/build.gradle --no-daemon --info dist makeSdk - 1
> Return Code: 1

What is the OS environment on your buildbot?  Specifically what is the /bin/sh program?

I can see the error seems to be that /bin/sh does not support "[[" operator.  However, this particular failing line was not introduced by my patch.  I wonder why it passed before.

Patch-set: 1
Reviewer: Gerrit User 1439078 <1439078@85c56323-6fa9-3386-8a01-6480fb634889>