Update patch set 1
Patch Set 1:

Hi David:
   when I compile on linux, I got following error:
./android/icons.h: In function 'android_icon_find':
./android/icons.h:5905:5: error: initializer element is not constant
the root cause is the "images_android_icon_128_png_len", when I change it to the 23093, the compilation succeeded. the same error happens to images_android_icon_256_png_len and images_android_icon_32_png_len
   after compilation, I do see the nice green icon works nicely :)

   for window, the compilation is successful without any of above changes; however, I don't know where to put the icons in the windows sdk directory so when I open emulator it complains that it cannot find the android_icon_32.png

Patch-set: 1