linux-user: Add missing includes
We're getting errors about this:
linux-user/elfload.c:2770:36: error: use of undeclared identifier 'MAP_FIXED_NOREPLACE'

Change-Id: Ib7cf26582ffb1fd9e0a8f64f22901ccb5d4a3653