fix gcc8 build error
error: global qualification of class name is invalid before ‘{’ token
struct ::vk_util::vk_fn_info::GetVkFnInfo<coreName> {

Removing the global qualification means the macro must be
used within the same namespace.

Test: compiled:
export CC=gcc-8 && export CXX=g++-8 && cmake . ../ && make

Change-Id: Ic5eee9791c751c420dd0e1fbaee0c11cfe8b04b1
(cherry picked from commit 5c451ff83feacc415847e7bf93e01b6e00a2c7d4)
Merged-In: Ic5eee9791c751c420dd0e1fbaee0c11cfe8b04b1