Update patch set 1
Patch Set 1:

So.. yeah, the symbol uploader does an improper find and does not log errors;

Running: ./android/scripts/upload-symbols.sh --symbol-dir=/usr/local/google/home/jansene/src/emu-master-dev-2/external/qemu/objs/build/symbols --verbose --verbose --crash-staging
ERROR: Corrupt symbol file /usr/local/google/home/jansene/src/emu-master-dev-2/external/qemu/objs/build/symbols/emugl64_common_host_unittests.sym.err
bash -c 
bash: -c: option requires an argument


We need to binplace the .err logs in a different location..

Patch-set: 1
Reviewer: Gerrit User 1125918 <1125918@85c56323-6fa9-3386-8a01-6480fb634889>