Update patch set 2
Patch Set 2:

Compiler complained about "undefined reference to `cpu_mips_hw_interrupts_pending'".  It seems that cpu_mips_hw_interrupts_pending is missing from target-mips/cpu.h in AOSP.  Please update.

Patch-set: 2
Label: Code-Review=0
Label: Verified=0