Fix Darwin dyld launch error.
This patch adds initializers to two global variables defined in
code-profile.c. When the variables are defined without initializers,
the compiler will place them in the object's file 'common section',
and for some reason, the static linker will not properly place them
in the final executable, but will _not_ complain about it ??

In the end, trying to run the executable (e.g. 'emulator64-arm -help')
generated a dyld error.

  dyld: Symbol not found: _code_profile_dirname
    Referenced from: /Volumes/Android/repo/aosp/external/qemu/objs/emulator64-x86
    Expected in: flat namespace
   in /Volumes/Android/repo/aosp/external/qemu/objs/emulator64-x86
  Trace/BPT trap: 5

This patch fixes the problem by adding initializers. Not that an
alternative would be to use -fno-common, but doing so introduces
many more breakages, so isn't a workable solution.

BUG=18234905

Change-Id: If7c8337f4ac4f7fa20d74f255ec4930efbd0d0be