Update patch set 4
Patch Set 4:

Breaks mac build:

Checking out files: 100% (3541/3541), done.ut files:  45% (1617/3541)   
Checking out files: 100% (4439/4439), done.ut files:  11% (524/4439)   
Checking out files: 100% (81/81), done.ng out files:  66% (54/81)   
Checking out files: 100% (10349/10349), done. files:   2% (221/10349)   
Syncing work tree: 100% (41/41), done.  

lfy-macbookpro:emu lfy$ cd external/qemu/
lfy-macbookpro:qemu lfy$ ./android/rebuild.sh 
Running: ./android/rebuild.sh 
Running: /Users/lfy/emu/external/qemu/android/scripts/config-cmake.sh 
ERROR: Configuration error, please run ./android/scripts/config-cmake.sh to see why.
lfy-macbookpro:qemu lfy$ ./android/scripts/config-cmake.sh --verbose
Running: ./android/scripts/config-cmake.sh --verbose
COMMAND: rm -rf objs
COMMAND: mkdir -p objs
COMMAND: eval /Users/lfy/emu/prebuilts/cmake/darwin-x86/bin/cmake -H/Users/lfy/emu/external/qemu -Bobjs -DCMAKE_TOOLCHAIN_FILE=/Users/lfy/emu/external/qemu/android/build/cmake/toolchain-darwin-x86_64.cmake -DOPTION_CRASHUPLOAD=NONE -DCMAKE_BUILD_TYPE=Release -G Ninja
CMake Warning at android/build/cmake/android.cmake:298 (message):
  Unable to retrieve git version from /Users/lfy/emu/external/qemu, out: ,
  err: fatal: No names found, cannot describe anything.

Call Stack (most recent call first):
  CMakeLists.txt:187 (get_git_version)


CMake Error at android/build/cmake/prebuilts.cmake:239 (message):
  The target emulator-libui_unittests depends on a dependency:
  /Users/lfy/emu/prebuilts/android-emulator-build/qt/darwin-x86_64/lib/libsoftokn3.dylib
  that does not exist.  Full list QT5_SHARED_DEPENDENCIES!
Call Stack (most recent call first):
  android/android-emu/android-libui.cmake:288 (android_target_dependency)
  android/android-emu/CMakeLists.txt:35 (include)


lfy-macbookpro:qemu lfy$

Patch-set: 4