Update patch set 2
Patch Set 2:

> Patch Set 2: Autosubmit+1 Code-Review+1

21:19:30(10:57.76) rel | /mnt/tmpfs/src/android/emu-master-dev/external/qemu/android/android-emugl/host/libs/libOpenglRender/vulkan/vk_util.h: In instantiation of ‘void vk_append_struct(vk_struct_chain_iterator*, T*) [with T = VkImportMemoryWin32HandleInfoKHR]’:
21:19:30(10:57.83) rel | /mnt/tmpfs/src/android/emu-master-dev/external/qemu/android/android-emugl/host/libs/libOpenglRender/vulkan/VkDecoderGlobalState.cpp:2067:63:   required from here
21:19:30(10:57.76) rel | /mnt/tmpfs/src/android/emu-master-dev/external/qemu/android/android-emugl/host/libs/libOpenglRender/vulkan/vk_util.h:238:5: error: incomplete type ‘vk_get_vk_struct_id<VkImportMemoryWin32HandleInfoKHR>’ used in nested name specifier
21:19:30(10:57.10) rel | vk_get_vk_struct_id<T>::id;
21:19:30(10:57.90) rel | ^

could be a missing define or include

Patch-set: 2
Reviewer: Gerrit User 1082465 <1082465@85c56323-6fa9-3386-8a01-6480fb634889>