Update patch set 7
Patch Set 7: Verified-1

I'm failing to build Qt.
I checked out patch set 7, ran download-sources.sh (success)
build-qt.sh failed:
jameskaye@alephnull:~/Emulators/qtTest-1.4d/external/qemu$ ./android/scripts/build-qt.sh 
WARNING: Unknown package field [BASENAME=qt-base] on line 20: /usr/local/google/home/jameskaye/Emulators/qtTest-1.4d/prebuilts/android-emulator-build/archive/PACKAGES.TXT
[linux-x86_64] Building Qt
ERROR: Cannot find version for package qt-base!
ERROR: [linux-x86_64] Could not build Qt!

"Cannot find version" makes me wonder if I'm missing an environment variable.

Patch-set: 7