Update patch set 1
Patch Set 1: Verified-1

That seems to break the compilation of aosp/master with the standalone build, e.g. missing X11 headers when building SDL from sources, also breaks android/kernel/kernel_utils.cpp with:

  .//android/kernel/kernel_utils.cpp: In function 'bool android_pathProbeKernelType(char const*, KernelType*)':
  .//android/kernel/kernel_utils.cpp:128:60: error: invalid conversion from 'char const*' to 'char*' [-fpermissive]
  make: *** [objs/intermediates/emulator-common/android/kernel/kernel_utils.o] Error 1

I'm looking into it.

Patch-set: 1