Update patch set 1
Patch Set 1:

> Patch Set 1:
> 
> So.. yeah, the symbol uploader does an improper find and does not log errors;
> 
> Running: ./android/scripts/upload-symbols.sh --symbol-dir=/usr/local/google/home/jansene/src/emu-master-dev-2/external/qemu/objs/build/symbols --verbose --verbose --crash-staging
> ERROR: Corrupt symbol file /usr/local/google/home/jansene/src/emu-master-dev-2/external/qemu/objs/build/symbols/emugl64_common_host_unittests.sym.err
> bash -c 
> bash: -c: option requires an argument
> 
> 
> We need to binplace the .err logs in a different location..

Ouch, thanks for the find. Let's also binplace the .err log in the artifacts so we can get that kind of  log from the build still if something happens there.

Patch-set: 1