Update patch set 8
Patch Set 8: Presubmit-Ready+1

> Patch Set 8:
> 
> Really strange error. The logs shows:
> 
> 153143 Protoc: studio_stats.pb.cc <-- android/android-emu/android/metrics/proto/studio_stats.proto¶  
> 
> <snip>
> 
> 153277 android/android-emu/android/skin/qt/extended-pages/camera-virtualscene-subpage.cpp:17:51: fatal error: android/metrics/proto/studio_stats.pb.h: No such file or directory¶                                        
> 153278  #include "android/metrics/proto/studio_stats.pb.h"¶
> 
> This part is still using our old build system:
> 
> - protoc didn't finish yet (we have bad dependency)
> 
> I'm running a dependency analysis now to see if we can learn something.

Turns out we have a dependency problem:

Dependency analysis:

$ make -Bnd | make2graph > dep.dot

Nodes of interest:

n4425[label="objs/build/intermediates64/proto-sources/android/metrics/proto/studio_stats.pb.h", color="green"];¶
n6684[label="android/android-emu/android/skin/qt/extended-pages/camera-virtualscene-subpage.cpp", color="green"];¶


$ python
>>> from networkx.drawing.nx_pydot import read_dot
>>> graph = read_dot('dep.dot')
>>> import networkx as nx

Check for the dependency between the two:

>>> nx.shortest_path(graph,'n4425','n6684')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jansene/homebrew/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/generic.py", line 142, in shortest_path
    paths = nx.bidirectional_shortest_path(G, source, target)
  File "/Users/jansene/homebrew/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 226, in bidirectional_shortest_path
    results = _bidirectional_pred_succ(G, source, target)
  File "/Users/jansene/homebrew/lib/python2.7/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 294, in _bidirectional_pred_succ
    raise nx.NetworkXNoPath("No path between %s and %s." % (source, target))
networkx.exception.NetworkXNoPath: No path between n4425 and n6684.

Ai, not good.  However we have:

>>> graph['n6684']
AdjacencyView({'n6683': {0: {}}})

With:
n6683[label="objs/build/intermediates64/emulator-libui/android/skin/qt/extended-pages/camera-virtualscene-subpage.o", color="red"];¶

(The .o file depends on the .cpp file)

And we have:

>>> nx.shortest_path(graph,'n4425','n6683')
['n4425', 'n6683']

So it looks like the pb.h is needed for the object file, but not for the cpp file. So the .cpp & pb.h can be created at the same time. In this case we didn't create the pb.h in time and hence the build failed with the error.

Patch-set: 8
Reviewer: Gerrit User 1125918 <1125918@85c56323-6fa9-3386-8a01-6480fb634889>
Label: Presubmit-Ready=+1