Update patch set 3
Patch Set 3:

> Patch Set 3:
> 
> > Patch Set 3: Code-Review+2
> 
> Hmm, looks like something is up with the windows build + mUi:
> 
> android/android-emu/android/skin/qt/image-well.cpp: In constructor 'ImageWell::ImageWell(QWidget*)':
> android/android-emu/android/skin/qt/image-well.cpp:19:24: error: class 'ImageWell' does not have any field named 'mUi'
>      : QWidget(parent), mUi(new Ui::ImageWell()) {
>                         ^
> android/android-emu/android/skin/qt/image-well.cpp:20:5: error: 'mUi' was not declared in this scope
>      mUi->setupUi(this);

android/android-emu/android/skin/qt/image-well.h:52:5: error: 'unique_ptr' in namespace 'std' does not name a type
     std::unique_ptr<Ui::ImageWell> mUi;

ah, missing C++ header most likely

Patch-set: 3
Reviewer: Lingfeng Yang <1082465@85c56323-6fa9-3386-8a01-6480fb634889>