Update patch set 9
Patch Set 9:

Weird, we have a mingw build failure due to generated protobuf code:

0:03:18.124661 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:105:3: error: expected identifier before numeric constant
0:03:18.124710 rel| ERROR_INVALID_OPERATION = 8
0:03:18.124757 rel| ^
0:03:18.124824 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:105:3: error: expected ‘}’ before numeric constant
0:03:18.124873 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:105:3: error: expected unqualified-id before numeric constant
0:03:18.124929 rel| In file included from /buildbot/src/android/emu-master-dev/external/qemu/android/android-emu/android/skin/qt/car-cluster-window.cpp:13:0:
0:03:18.124981 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:108:7: error: ‘Status’ does not name a type
0:03:18.125028 rel| const Status Status_MIN = RESULT_OK;
0:03:18.125075 rel| ^
0:03:18.125122 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:109:7: error: ‘Status’ does not name a type
0:03:18.125168 rel| const Status Status_MAX = ERROR_INVALID_OPERATION;
0:03:18.125214 rel| ^
0:03:18.125262 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:110:30: error: ‘Status_MAX’ was not declared in this scope
0:03:18.125308 rel| const int Status_ARRAYSIZE = Status_MAX + 1;
0:03:18.125351 rel| ^
0:03:18.125398 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h: In static member function ‘static const VehicleAreaConfig* VehicleAreaConfig::internal_default_instance()’:
0:03:18.125448 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:153:17: error: ‘_VehicleAreaConfig_default_instance_’ was not declared in this scope
0:03:18.125492 rel| &_VehicleAreaConfig_default_instance_);
0:03:18.125533 rel| ^
0:03:18.125575 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:153:17: note: suggested alternative:
0:03:18.125617 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:56:45: note:   ‘emulator::_VehicleAreaConfig_default_instance_’
0:03:18.125659 rel| extern VehicleAreaConfigDefaultTypeInternal _VehicleAreaConfig_default_instance_;
0:03:18.125705 rel| ^
0:03:18.125751 rel| In file included from /buildbot/src/android/emu-master-dev/external/qemu/android/android-emu/android/skin/qt/car-cluster-window.cpp:13:0:
0:03:18.125813 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h: In static member function ‘static const VehiclePropConfig* VehiclePropConfig::internal_default_instance()’:
0:03:18.125864 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:318:17: error: ‘_VehiclePropConfig_default_instance_’ was not declared in this scope
0:03:18.125911 rel| &_VehiclePropConfig_default_instance_);
0:03:18.125969 rel| ^
0:03:18.126011 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:318:17: note: suggested alternative:
0:03:18.126060 rel| In file included from /buildbot/src/android/emu-master-dev/external/qemu/android/android-emu/android/skin/qt/car-cluster-window.cpp:13:0:
0:03:18.126107 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:59:45: note:   ‘emulator::_VehiclePropConfig_default_instance_’
0:03:18.126148 rel| extern VehiclePropConfigDefaultTypeInternal _VehiclePropConfig_default_instance_;
0:03:18.126191 rel| ^
0:03:18.126234 rel| In file included from /buildbot/src/android/emu-master-dev/external/qemu/android/android-emu/android/skin/qt/car-cluster-window.cpp:13:0:
0:03:18.126276 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h: In static member function ‘static const VehiclePropValue* VehiclePropValue::internal_default_instance()’:
0:03:18.127808 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:533:17: error: ‘_VehiclePropValue_default_instance_’ was not declared in this scope
0:03:18.127983 rel| &_VehiclePropValue_default_instance_);
0:03:18.128062 rel| ^
0:03:18.128111 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:533:17: note: suggested alternative:
0:03:18.128153 rel| In file included from /buildbot/src/android/emu-master-dev/external/qemu/android/android-emu/android/skin/qt/car-cluster-window.cpp:13:0:
0:03:18.128193 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:65:44: note:   ‘emulator::_VehiclePropValue_default_instance_’
0:03:18.128232 rel| extern VehiclePropValueDefaultTypeInternal _VehiclePropValue_default_instance_;
0:03:18.128271 rel| ^
0:03:18.128309 rel| In file included from /buildbot/src/android/emu-master-dev/external/qemu/android/android-emu/android/skin/qt/car-cluster-window.cpp:13:0:
0:03:18.128347 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h: In static member function ‘static const VehiclePropGet* VehiclePropGet::internal_default_instance()’:
0:03:18.128386 rel| android/android-emu/android/emulation/proto/VehicleHalProto.pb.h:745:17: error: ‘_VehiclePropGet_default_instance_’ was not declared in this scope

Patch-set: 9
Reviewer: Gerrit User 1082465 <1082465@85c56323-6fa9-3386-8a01-6480fb634889>