Fix OSX build caused by a typo in include
Build server seems more strict and errors out
with following error:

fatal error: 'GLcommon/GlLibrary.h' file not found

Change-Id: I4d8f5e2a125435161927ee31f8cfa97495309970