Try new host toolchain
Fallback to the previous host toolchain if new one
can't be found.  Also fix an issue which reads

  external/qemu/android/kernel/kernel_utils.cpp: In function 'bool android_pathProbeKernelType(char const*, KernelType*)':
  external/qemu/android/kernel/kernel_utils.cpp:128:60: error: invalid conversion from 'char const*' to 'char*' [-fpermissive]

Turns out there are two strstr prototypes in the new glibc2.11 string.h,

Change-Id: Id7bba0bdc9ff4a691235937535907316ff83156a