Revert "Set uid and gid to AID_SYSTEM 1000 when creating user data image"
This is making the /data/app showing up with wrong key
and causing cts regression

CtsContentTestCases
CtsSecurityTestCases
junit.framework.AssertionFailedError: These packages should not be 
signed with a well known key: [com.android.gesture.builder, 
com.example.android.apis, com.android.smoketest.tests,
com.android.smoketest

BUG: 

This reverts commit 1c829e6f3be1bf96a73d4284fb2ae89e58099440.

Change-Id: Id468ee9a52386a5229e84c3ac1939a4caccd370e